//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tugas_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_T_TransactionItem
    {
        public int Id { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> TB_M_Item_id { get; set; }
        public Nullable<int> TB_M_Sell_id { get; set; }
    
        public virtual TB_M_Item TB_M_Item { get; set; }
        public virtual TB_M_Sell TB_M_Sell { get; set; }
    }
}
